# Generated by Django 5.0.3 on 2024-03-20 16:33

import appResponseData.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appResponseData', '0003_alter_generatetab_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatedata',
            name='status',
            field=models.BooleanField(blank=True, default=True, help_text='Да (Активный) / Нет (Неактивный)', null=True, verbose_name='Разрешение'),
        ),
        migrations.AlterField(
            model_name='generatetab',
            name='number',
            field=models.PositiveIntegerField(default=appResponseData.utils.generate_number, verbose_name='Число'),
        ),
    ]
